edgeserver:
  build: docker/edgeserver
  ports:
    - "8082:8082"
  links:
    - storageserver
    - emailservice
  volumes:
    - ./data/edgeserver_data:/edgeserver_data
eventservice:
  build: docker/eventservice
  ports:
    - "8084:8084"
  links:
    - storageserver
    - emailservice
  volumes:
    - ./data/eventservice_data:/eventservice_data
storageserver:
  build: docker/storageserver
  ports:
    - "8081:8081"
  volumes:
    - ./data/maven_repo:/root/.m2
    - ./data/storageserver_data:/storageserver_data
emailservice:
  build: docker/emailservice
  ports:
    - "8083:8083"
  volumes:
    - ./data/emailservice_data:/emailservice_data

