edgeserver:
  build: docker/edgeserver
  ports:
    - "80:8082"
  links:
    - storageserver
    - emailservice
  volumes:
    - ./data/edgeserver_data:/edgeserver_data
eventservice:
  build: docker/eventservice
  links:
    - storageserver
    - emailservice
  volumes:
    - ./data/eventservice_data:/eventservice_data
storageserver:
  build: docker/storageserver
  volumes:
    - ./data/maven_repo:/root/.m2
    - ./data/storageserver_data:/storageserver_data
emailservice:
  build: docker/emailservice
  volumes:
    - ./data/emailservice_data:/emailservice_data

