edgeserver:
  build: docker/edgeserver
  ports:
    - "8002:8082"
  links:
    - storageserver
    - emailservice
  volumes:
    - ./data/edgeserver_data:/edgeserver_data
eventservice:
  build: docker/eventservice
  links:
    - storageserver
    - emailservice
  volumes:
    - ./data/eventservice_data:/eventservice_data
importmswservice:
  build: docker/importmswservice
  links:
    - storageserver
  volumes:
    - ./data/importmswservice_data:/importmswservice_data
storageserver:
  build: docker/storageserver
  volumes:
    - ./data/maven_repo:/root/.m2
    - ./data/storageserver_data:/storageserver_data
emailservice:
  build: docker/emailservice
  volumes:
    - ./data/emailservice_data:/emailservice_data

